### ISSUE TITLE
[Profil] Testfälle erstellen

### ISSUE THREAD

**Issue by mrnhrst** [WWI14AMB/WAPlugin#14]
Testfälle erstellen. Die Testfälle werden kontinuierlich erarbeitet und sind nicht an einen bestimmten Meilenstein gebunden.

**Comment by alxndr13** [comment]
Wie ist hier der Stand? Da sollte doch Harald was machen

**Comment by EmreDuelger** [comment]
Jens hat Testfälle erstellt und die Dokumentation dazu in der Dropbox abgelegt. Er wird noch die Formulare testen, deshalb werden noch Testfälle dazu kommen.

**Comment by alxndr13** [comment]
@EmreDuelger super! @jensbek kannst du das noch auf eure Wikiseite stellen?

**Comment by EmreDuelger** [comment]
Ist auf unserer Wikiseite verlinkt.
