### ISSUE TITLE
[Profil] Mockups & Anordnung pro Formular

### ISSUE THREAD

**Issue by mrnhrst** [WWI14AMB/WAPlugin#20]
Mockups & Anordnung pro Formular und notwendige Elemente bereitstellen pro Formular

**Comment by EmreDuelger** [comment]
Max und Maria haben die Mockups erstellt.

**Comment by Verokas** [comment]
Es fehlen noch die Mockups für das Bearbeiten der Profile

**Comment by EmreDuelger** [comment]
Mockups für das Bearbeiten der Profile wurden ergänzt.
