### ISSUE TITLE
[Themen] Rollen z.B. "Geeignet für..."

### ISSUE THREAD

**Issue by mrnhrst** [WWI14AMB/WAPlugin#27]
Rollen z.B. für "Geeignet für..." --> bitte verantwortliche Person zuweisen und Issue aussagekräftiger benennen.

**Comment by jambalaja9** [comment]
"Geeignet für" war meinem Verständnis nach :
Projektarbeit 1
Projektarbeit 2
Bachelorarbeit
und nicht für Rollen oder?

Korrigiert mich wenn ich da falsch liege.

**Comment by EmreDuelger** [comment]
Ja, so wie du verstanden hast. Aber wo speichert ihr diesen Zustand in der Datenbank?

**Comment by EugenLenz** [comment]
Das was Raphael gesagt hat stimmt. Mit "Geeignet für" ist die Eignung für welche Arbeit das Thema ist gemeint. Wie Emre gesagt hat, fehlt es noch im Datenmodell und muss ergänzt werden.

**Comment by EmreDuelger** [comment]
@Paddy420  Bitte im Datenmodell ergänzen.

**Comment by jambalaja9** [comment]
Alex, uns fehlt beim Thema noch das Attribut geeignet_fuer

da soll dann zwischen PA1, PA2 und BA unterschieden werden.

Sollte ein Mehrwertiges Feld werden.

**Comment by Verokas** [comment]
Mit Raphael besprochen: Beim Wechsel der Stati von "offen" in "in Klärung" sollte das Feld "geeignet für" eindeutig belegt werden (davor war es optional mit möglicher Mehrfachnennung)

Für den Dozenten ist es ja wichtig zu wissen, ob der Student eine PA1, PA2 oder BA schreiben möchte.
(Außerdem können durch die eindeutige Zuweisung die PA- und BA-Themen im Profil direkt als solche angezeigt werden)
