### ISSUE TITLE
[Themen] Messaging API oder sendmail klären

### ISSUE THREAD

**Issue by mrnhrst** [WWI14AMB/WAPlugin#29]
[Themen] Messaging API oder sendmail klären (PHP)

**Comment by jambalaja9** [comment]
Ist die gleiche Problematik wie #30 
Überlegungen schon in #8

**Comment by jambalaja9** [comment]
Ich schreibs mal hier rein:

Am einfachsten ist es, wenn wir einen SMTP Server haben und dann die sendmail()-Funktion von Php nutzen. Habe die Message API zwar auch angeschaut, aber ich hab sie nicht zum laufen bekommen.
Leider ist die auch nicht so weit dokumentiert, dass ich sagen würde wir bekommen das in der Gruppe einigermaßen schnell hin. 
Vielleicht raff ich die API auch einfach nicht und das ist ganz einfach, aber im Moment komm ich da nicht weiter.

Vorschlag deshalb: sendmail() von PHP wenn wir nen SMTP Server haben

**Comment by alxndr13** [comment]
Hast du hier was wegen der Message API rausgefunden?

**Comment by alxndr13** [comment]
@jambalaja9 ?
