### ISSUE TITLE
[Doku] Versionierungsstrategie festlegen

### ISSUE THREAD

**Issue by mrnhrst** [WWI14AMB/WAPlugin#51]
Versionierungsstrategie festlegen

Verantwortliche zuordnen über "Assignees"

**Comment by alxndr13** [comment]
http://semver.org/

evtl. hilfreich

**Comment by laissez-faire** [comment]
Erledigt. Strategie wird näher erklärt und deutlich in der Dropbox. Unter: Projekt\DOKUMENTATION\Moodle-Projekt Wichtige Infos.docx
