### ISSUE TITLE
[Thema] Themenbearbeitung

### ISSUE THREAD

**Issue by Verokas** [WWI14AMB/WAPlugin#52]
- Link zum Bearbeitungsmodus von der Themenansicht. (Von der Themenüberischt im Profil aus landen wir immer nur bei der Ansichtsseite eines Themas, Bearbeitungsmodus würde dann von eurer Seite aus angesteuert werden)
- Thema löschbar? Sollen zumindest nicht mehr bei offenen angezeigt werden

**Comment by jambalaja9** [comment]
Mein Vorschlag:
Wie ihr schon sagt: Von der Themenüberischt im Profil aus landen wir immer nur bei der Ansichtsseite eines Themas, Bearbeitungsmodus würde dann von eurer Seite aus angesteuert werden.

Das wir einen Button hinzufügen, von dem man dann in den Bearbeitungsmodus gelangt.

Löschen haben wir ja eig. gesagt wollen wir nicht machen. (Wenn ich mich richtig an letztes Semester erinnere war das, weil alle Themen ja als Orientierung für andere gelten sollten.)
Deshalb würde ich auch dabei bleiben und evtl einen 4. Status hinzufügen, sodass das Thema nur nicht mehr auf der Profil-Übersichtsseite angezeigt wird, aber immer noch bei allen Themen zu finden ist.

**Comment by EugenLenz** [comment]
Also die Überlegung und Festlegung haben wir mit Emre und Axel getroffen:

Wir werden 4 Statis haben:
belegt
offen
in Klärung
abgeschlossen

Bei "abgeschlossen" hatten wir die Überlegung, dass wir diesen in einen weiteren Status aufteilen, bzw. einen fünften hinzunehmen. Dieser wäre "abgebrochen". Dieser Status soll die nicht abgeschlossen Themen zur Übersicht darstellen und zur Themenfindung helfen.

Die Frage die ich jetzt in die Runde stelle ist, ob wir einen fünften Status hinzunehmen sollten oder uns auf 4 festlegen, sodass abgeschlossen "Abbruch" sowie "Fertigstellung" beinhaltet.

**Comment by EmreDuelger** [comment]
Ich denke schon, dass wir in "Abbruch" und "Fertigstellung" differenzieren sollten.

**Comment by leonkratz** [comment]
In der Doku vom 1. Semester tauchen noch "weitergeitet", "in Rücksprache" und "offen/bearbeitet" als möglicher Status für ein Thema auf.
Entfallen die dann?
Wenn ja, würde ich sagen, dass wir statt der oben genannten dann immer "in Klärung" als Status angeben.

**Comment by Verokas** [comment]
Wir haben uns mit Raphael auf folgende Stati mit folgenden Statuscodes geeinigt:

offen : 0
in Klärung : 1
belegt : 2
abgeschlossen : 3
abgebrochen : 4

**Comment by alxndr13** [comment]
Dokumentiert ihr das im Wiki? Dann hats Sabine einfacher :)

**Comment by leonkratz** [comment]
Ist im Wiki dokumentiert
