### ISSUE TITLE
[Profil] Researchgate Webscraper für Publikationen erstellen

### ISSUE THREAD

**Issue by Paddy420** [WWI14AMB/WAPlugin#53]
Webscraper der von Researchgate-Profillink die Publikationen automatisch bezieht und an die Datenbank weitergibt.

**Comment by Paddy420** [comment]
Script funktioniert mittlerweile.
HTTP 429 Error könnte jedoch problematisch werden.
Nächste Schritte: Mit Moodle verknüpfen und variable Researchgate-URLs verwenden.

**Comment by alxndr13** [comment]
Was wenn du das gescrapte Ergebnis in nem File im moodledata Verzeichnis ablegst und wir via Cronjob das Skript nur einmal pro Tag oder pro Woche aufrufen? Müsste ja eigentlich reichen

**Comment by Paddy420** [comment]
Das könnte man zur Aktualisierung machen. Aber die Daten werden ja sowieso in die Datenbank geschrieben, also wird das Skript nur einmal aufgerufen und die Daten dann in die DB geschrieben und von da aus auch angezeigt.

**Comment by EmreDuelger** [comment]
Da der Webscraper geschrieben wurde, schließe ich den hier.
