### ISSUE TITLE
Startseite pro Teilprojekt erstellen

### ISSUE THREAD

**Issue by alxndr13** [WWI14AMB/WAPlugin#74]
Jedes Teilprojekt sollte eine eigene Einstiegsseite haben.

Suche -> suche.php
Profil -> profil.php
Themen -> themen.php

Wo eure Einsteigsseite liegt, ist mir egal. Themen hat bereits einen Unterordner erstellt, bietet sich an dass andere dieser Struktur folgen.

**Comment by EmreDuelger** [comment]
Unsere ist im Ordner Profil und heißt "index.php". Ich habe gesehen jede Gruppe hat eine "Startseite". Somit schließe ich den Issue.
