### ISSUE TITLE
Doku Technik Install

### ISSUE THREAD

**Issue by mrnhrst** [WWI14AMB/WAPlugin#75]
Erstellung der Doku (Welche Tools und was eingerichtet werden muss.
- Vagrant
- VM

für @alxndr13  und @laissez-faire nur zur Info :-)

**Comment by alxndr13** [comment]
@mrnhrst wie weit bist du da?

**Comment by mrnhrst** [comment]
Fertiggestellt (Abgelegt im Doku-Ordner in der Dropbox)
