### ISSUE TITLE
[Thema] Der Workflow

### ISSUE THREAD

**Issue by leonkratz** [WWI14AMB/WAPlugin#77]
Hier nochmal gebündelt alle relevanten Informationen zum Workflow.
Die Issues 52, 27 und 25 können geschlossen werden.

Ein Thema kann fünf verschiedene Stati haben.

0 - Offen
1 - In Klärung 
2- Belegt
3 - Geschlossen
4 - Abgebrochen

Wird ein neues Thema erstellt, erhält es den Status Offen. Sobald sich ein Student auf ein Thema bewirbt oder bei einem Doznten bzgl. eines Themas anfragt, ändert sich der Status auf In Klärung. Nun gibt es drei Varianten um fortzufahren. Verwirft der Ersteller das Thema wieder, ändert sich der Status auf Abgebrochen. Eine Themenlöschung soll nicht erfolgen. Lehnt der Dozent die Bewerber ab, ist der Status wieder Offen. Können sich Student und Dozent auf das Thema einigen, ist Belegt der neue Status des Themas. Nun beginnt die Bearbeitungsphase. Ist diese Phase beendet, wird das Thema Geschlossen. Wird das Thema aus irgendwelchen Gründen nicht beendet, ist Abgebrochen der finale Status.

Wer für die Statusänderung verantwortlich ist, muss noch geklärt werden.

Sobald der Stati von Offen auf In Klärung wechselt, wird das Feld "geeignet für" angezeigt. Es soll eindeutig mit PA1. PA2 oder BA belegt werden. 
Bei der Erstellung des Thema ist dies optional - Mehrfachnennung ist möglich.
Für den Dozenten ist es wichtig zu wissen, ob der Student PA1, PA2 oder BA schreiben möchte. Durch eine eindeutige Zuordnung der PA- und BA-Themen können diese im Profil direkt als solche angezeigt werden.

Ergänzt mich, wenn ich was vergessen habe bzw etwas falsch ist.

**Comment by marianiki** [comment]
Zu den Verantwortlichkeiten:

Initial ist der Verfasser bei Themenerstellung auch der Bearbeiter. Generell dürfen nur Bearbeiter Status ändern und Thema bearbeiten. 
Sobald der Status wieder mit "offen" belegt wurde, wird der aktuelle Bearbeiter als Bearbeiter ausgetragen. Wenn niemand als Bearbeiter hinterlegt ist, darf jeder den Status ändern. Sobald jemand den Status (außer mit "offen") ändert, wird er als Bearbeiter hinterlegt.

**Comment by jambalaja9** [comment]
hiermit ist der worklfow ja geklärt. müssen es dann nur noch in die implementierung übernehmen.
