### ISSUE TITLE
Messaging?

### ISSUE THREAD

**Issue by alxndr13** [WWI14AMB/WAPlugin#8]
Wie wird kommuniziert? Mail, internes Messging?

**Comment by jambalaja9** [comment]
2 Möglichkeiten:

Messaging API oder php sendmail
1. hat größeren Implementierungsaufwand
2. benötigt wahrscheinlich einen SMTP Server

**Comment by ThommyZ** [comment]
Hier der Link zur Messaging API:
https://docs.moodle.org/dev/Message_API

Hier der Link Php Sendmail:
https://secure.php.net/manual/de/function.mail.php

**Comment by alxndr13** [comment]
Folgender Plan: 
wenn mit geringem Aufwand <1-2 Stunden möglich, dann nehmen wir die Messaging API, wenn nicht dann Sendmail - ich frage mal nach dem DHBW SMTP Server, da brauchen wir aber wahrscheinlich für den Mailversand ne VPN Conn.
