### ISSUE TITLE
Spaltenname in der Datenbank ändern

### ISSUE THREAD

**Issue by Verokas** [WWI14AMB/WAPlugin#99]
Bitte in der Tabelle "mdl_waplugin_cv_ereignis" den Spaltenname von "Tätigkeit" in "Taetigkeit" ändern, weil Moodle damit Probleme hat.

**Comment by alxndr13** [comment]
ist im master gefixt, musst deinen branch mit dem stand aus dem master updaten und die VM neu bauen :)
